version: '2'

services:

  bibliomap-harvester:
    container_name: bibliomap-harvester
    image: node:6.9.1
    volumes:
      - .:/app
    working_dir: /app
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
      BBH_ENRICHER_HOST: "bibliomap-enricher"
      BBH_ENRICHER_PORT: 27777
      BBH_LOGSTREAMS: ${BBH_LOGSTREAMS}
      BBH_LOG_FOLDER: ${BBH_LOG_FOLDER}


    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    entrypoint: ./docker-entrypoint.njs
